# Generated by Django 2.2.3 on 2019-07-04 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0014_auto_20190626_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2019, 7, 4, 17, 49, 51, 941738))),
                ('hora', models.TimeField()),
                ('codiexamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.examenes')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=10)),
                ('apellido_mat', models.CharField(max_length=10)),
                ('fecha_nac', models.DateTimeField(default=datetime.datetime(2019, 7, 4, 17, 49, 51, 940741))),
                ('ocupacion', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('prevision', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='agenda',
        ),
        migrations.DeleteModel(
            name='paciente',
        ),
        migrations.AddField(
            model_name='servicios',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.usuario'),
        ),
    ]
